[package]
name = "mini-bank"
version = "0.1.0"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
frame-support.workspace = true
frame-system.workspace = true

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
]